# Air Quality Analysis of Thomas Fire

Author: Haejin Kim

Repository: 
    
## About

This project aims to generate a false color image illustrating the fire scar left by the 2017 Thomas fire. The task involves utilizing Air Quality Index (AQI) data from the US Environmental Protection Agency to visualize the impact of the Thomas Fire on air quality in Santa Barbara County.

## Highlights 


## About the data 

#### 1) Landsat Collection 2 Level-2 Atmospherically Corrected Surface Reflectance Data:
This dataset comprises simplified bands (red, green, blue, near-infrared, and shortwave infrared) derived from the Landsat Collection 2 Level-2 atmospherically corrected surface reflectance data, collected by the Landsat 8 satellite. The data underwent preprocessing in the Microsoft Planetary Computer, involving the removal of non-land data and spatial resolution reduction (Landsat Collection in MPC). It is intended for visualization purposes only.

#### 2) California State Fire Perimeters 2017:
A shapefile detailing fire perimeters in California during 2017. The complete file is accessible via the CA state geoportal.

#### 3) Air Quality Data for 2017 and 2018:
This dataset was obtained from the EPA data portal. It contains 10 columns with information about statename, countyname, AQI, Defining Parameter, and Date. For the purpose of this analysis, the following columns will be utilized:

- statename
- countyname
- AQI
- Defining Parameter
- Date


## Final Output


## Import libraries

In [15]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches # for creating legends

import xarray as xr
import rioxarray as rioxr
import geopandas as gpd

from rasterio.features import rasterize # for rasterizing polygons

ModuleNotFoundError: No module named 'xarray'

In [16]:
pd.set_option('display.max_columns', None)

# Import Data

In [17]:
# air quality data from EPA
aqi_17 = pd.read_csv("https://aqs.epa.gov/aqsweb/airdata/daily_aqi_by_county_2017.zip")
aqi_18 = pd.read_csv("https://aqs.epa.gov/aqsweb/airdata/daily_aqi_by_county_2018.zip")

In [18]:
# open landsat perimeters in california
landsat = rioxr.open_rasterio('data/landsat8-2018-01-26-sb-simplified.nc')
landsat

NameError: name 'rioxr' is not defined

In [12]:
## read data one of dataset 
aqi_17.head()

,State Name,county Name,State Code,County Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting
0,Alabama,Baldwin,1,3,2017-01-01,21,Good,PM2.5,01-003-0010,1
1,Alabama,Baldwin,1,3,2017-01-04,22,Good,PM2.5,01-003-0010,1
2,Alabama,Baldwin,1,3,2017-01-10,19,Good,PM2.5,01-003-0010,1
3,Alabama,Baldwin,1,3,2017-01-13,30,Good,PM2.5,01-003-0010,1
4,Alabama,Baldwin,1,3,2017-01-16,16,Good,PM2.5,01-003-0010,1

In [13]:
# solve exercise here_
aqi = pd.concat([aqi_17, aqi_18], ignore_index=True)
aqi

,State Name,county Name,State Code,County Code,Date,AQI,Category,Defining Parameter,Defining Site,Number of Sites Reporting
0,Alabama,Baldwin,1,3,2017-01-01,21,Good,PM2.5,01-003-0010,1
1,Alabama,Baldwin,1,3,2017-01-04,22,Good,PM2.5,01-003-0010,1
2,Alabama,Baldwin,1,3,2017-01-10,19,Good,PM2.5,01-003-0010,1
3,Alabama,Baldwin,1,3,2017-01-13,30,Good,PM2.5,01-003-0010,1
4,Alabama,Baldwin,1,3,2017-01-16,16,Good,PM2.5,01-003-0010,1
...,...,...,...,...,...,...,...,...,...,...
654333,Wyoming,Weston,56,45,2018-12-27,36,Good,Ozone,56-045-0003,1
654334,Wyoming,Weston,56,45,2018-12-28,35,Good,Ozone,56-045-0003,1
654335,Wyoming,Weston,56,45,2018-12-29,35,Good,Ozone,56-045-0003,1
654336,Wyoming,Weston,56,45,2018-12-30,31,Good,Ozone,56-045-0003,1
654337,Wyoming,Weston,56,45,2018-12-31,35,Good,Ozone,56-045-0003,1